In [ ]:
#open the file 

import pandas as pd

In [ ]:
df = pd.read_csv("../data/data_14-12-2025.csv")

In [ ]:
df1 = pd.read_csv('../data/data_15-12-2025.csv')
df1.head(2)

In [ ]:
df.head(2)

In [ ]:



df.describe()

In [ ]:
df1 = df[df['Quantity'] <= 0]
df1

In [ ]:
df2 = df[df['UnitPrice'] <0]
df2

In [ ]:
df.head(5)

In [ ]:
df.info()

In [ ]:
df.shape

In [ ]:
df['Country'].value_counts()

In [ ]:
df['InvoiceDate'].value_counts()

In [ ]:
df.isna().sum()

In [ ]:


df.columns

In [ ]:


from datetime import datetime
import pandas as pd




df = pd.DataFrame()



df['date']=datetime.now()


df

In [5]:


url = 'https://raw.githubusercontent.com/SaiD-MH/E-Commerce-ETL-Data-Pipeline/main/data/data_13-12-2025.csv'


df = pd.read_csv(url)

df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
10092,537225,22831,WHITE BROCANTE SOAP DISH,2,12/5/2010 16:41,2.95,12748.0,United Kingdom
10093,537225,20757,RED DAISY POCKET BOOK,3,12/5/2010 16:41,0.85,12748.0,United Kingdom
10094,537225,20757,RED DAISY POCKET BOOK,6,12/5/2010 16:41,0.85,12748.0,United Kingdom
10095,537225,20764,ABSTRACT CIRCLES SKETCHBOOK,1,12/5/2010 16:41,3.75,12748.0,United Kingdom
10096,537225,20770,ABSTRACT CIRCLE JOURNAL,1,12/5/2010 16:41,2.55,12748.0,United Kingdom

In [8]:
df = pd.DataFrame({'a':[1] , 'b':[2]})
cols = ['a']

x = set(cols) - set(df.columns)

x

set()

In [3]:
from datetime import datetime


x = datetime.now()

print(x)

2025-12-31 16:25:36.347808

In [6]:
import pandas as pd

df = pd.DataFrame([{
    "InvoiceNo": "536365",
    "StockCode": "85123A",
    "Description": "WHITE HANGING HEART T-LIGHT HOLDER",
    "Quantity": 6,
    "InvoiceDate": "2010-12-01",
    "UnitPrice": 2.55,
    "CustomerID": 17850,
    "Country": "United Kingdom",
    "ingestion_date": pd.to_datetime("2025-12-31 16:25:36.347808")
    }])

df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,ingestion_date
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01,2.55,17850,United Kingdom,2025-12-31 16:25:36.347808