In [ ]:
#open the file 

import pandas as pd

In [ ]:
df = pd.read_csv("../data/data_14-12-2025.csv")

In [ ]:
df1 = pd.read_csv('../data/data_15-12-2025.csv')
df1.head(2)

In [ ]:
df.head(2)

In [ ]:



df.describe()

In [ ]:
df1 = df[df['Quantity'] <= 0]
df1

In [ ]:
df2 = df[df['UnitPrice'] <0]
df2

In [ ]:
df.head(5)

In [ ]:
df.info()

In [ ]:
df.shape

In [ ]:
df['Country'].value_counts()

In [ ]:
df['InvoiceDate'].value_counts()

In [ ]:
df.isna().sum()

In [ ]:


df.columns

In [ ]:


from datetime import datetime
import pandas as pd




df = pd.DataFrame()



df['date']=datetime.now()


df

In [2]:

import pandas as pd
url = 'https://raw.githubusercontent.com/SaiD-MH/E-Commerce-ETL-Data-Pipeline/main/data/data_13-12-2025.csv'


df = pd.read_csv(url)

len(df)

10097

In [8]:
df = pd.DataFrame({'a':[1] , 'b':[2]})
cols = ['a']

x = set(cols) - set(df.columns)

x

set()

In [3]:
from datetime import datetime


x = datetime.now()

print(x)

2025-12-31 16:25:36.347808

In [6]:
import pandas as pd

df = pd.DataFrame([{
    "InvoiceNo": "536365",
    "StockCode": "85123A",
    "Description": "WHITE HANGING HEART T-LIGHT HOLDER",
    "Quantity": 6,
    "InvoiceDate": "2010-12-01",
    "UnitPrice": 2.55,
    "CustomerID": 17850,
    "Country": "United Kingdom",
    "ingestion_date": pd.to_datetime("2025-12-31 16:25:36.347808")
    }])

df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,ingestion_date
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01,2.55,17850,United Kingdom,2025-12-31 16:25:36.347808

In [4]:




d1 = {"A":1}
d2 = {"A":1}

if d1 == d2:
    print("Y")
else:
    print("N")

Y

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "raw_sales_id": [1, 2, 3],
    "invoice_number": ["INV-1001", "INV-1002", "INV-1003"],
    "stock_code": ["S001", "S002", "S003"],
    "description": ["White T-Shirt", "Blue Jeans", "Sneakers"],
    "quantity": [3, 1, 2],
    "invoice_date": [
        pd.Timestamp("2025-01-01 10:15:00"),
        pd.Timestamp("2025-01-02 14:30:00"),
        pd.Timestamp("2025-01-03 18:45:00"),
    ],
    "unit_price": [19.99, 49.50, 89.99],
    "customer_id": ["CUST-01", None, "CUST-02"],
    "country": ["United Kingdom", "Germany", "France"],
    "ingestion_date": [
        pd.Timestamp("2025-01-01 10:20:00"),
        pd.Timestamp("2025-01-02 14:35:00"),
        pd.Timestamp("2025-01-03 18:50:00"),
    ],
})

df.head()

,raw_sales_id,invoice_number,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,ingestion_date
0,1,None,S001,White T-Shirt,3,2025-01-01 10:15:00,19.99,CUST-01,United Kingdom,2025-01-01 10:20:00
1,2,INV-1002,S002,Blue Jeans,1,2025-01-02 14:30:00,49.50,None,Germany,2025-01-02 14:35:00
2,3,INV-1003,S003,Sneakers,2,2025-01-03 18:45:00,89.99,CUST-02,France,2025-01-03 18:50:00

In [5]:





import pandas as pd

df1 = pd.DataFrame({
    'id':[1,2,3]
})

df2 = pd.DataFrame({
    'id': [1,2],
    'name':['Mohamed' , 'Khaled']
})



df = df1.merge(df2,how='left',on=['id'] ,indicator=True)
df

   id     name     _merge
0   1  Mohamed       both
1   2   Khaled       both
2   3      NaN  left_only

In [9]:
import pandas as pd

df = pd.DataFrame({"invoice_date": [
        pd.Timestamp("2025-01-01 10:15:00"),
        pd.Timestamp("2025-01-02 14:30:00"),
        pd.Timestamp("2025-01-04 18:45:00"),
    ]})

df['date_key'] = df['invoice_date'].apply(lambda x: int(x.strftime("%Y%m%d")))
df['full_date'] = df['invoice_date'].apply(lambda x: x.date())
df['day_of_week'] = df['invoice_date'].apply(lambda x: x.date().weekday()+ 1)
df['day_of_week'] = df['invoice_date'].apply(lambda x: x.date().day)
df['day_name'] = df['invoice_date'].apply(lambda x: x.date().strftime("%A"))
df['week_of_year'] = df['invoice_date'].apply(lambda x: x.date().isocalendar()[1])
df['month'] = df['invoice_date'].apply(lambda x: x.date().month)
df['month_name']=df['invoice_date'].apply(lambda x: x.date().strftime("%B"))
df['quarter']=df['invoice_date'].apply(lambda x: (x.date().month - 1 )// 3 + 1)
df['year'] = df['invoice_date'].apply(lambda x: x.date().year)
df['is_weekend'] = df['invoice_date'].apply(lambda x: x.date().weekday() >= 5)
df

,invoice_date,date_key,full_date,day_of_week,day_name,week_of_year,month,month_name,quarter,year,is_weekend
0,2025-01-01 10:15:00,20250101,2025-01-01,1,Wednesday,1,1,January,1,2025,False
1,2025-01-02 14:30:00,20250102,2025-01-02,2,Thursday,1,1,January,1,2025,False
2,2025-01-04 18:45:00,20250104,2025-01-04,4,Saturday,1,1,January,1,2025,True

In [ ]:
import uuid
import pandas as pd

df = pd.DataFrame({
    'x' : [1,2,3]
})


df['col2'] = df['x'].apply(lambda x: uuid.uuid1())
df

   x                                  col2
0  1  70d04f55-eb2b-11f0-9810-000c2943d053
1  2  70d0504a-eb2b-11f0-ad33-000c2943d053
2  3  70d05094-eb2b-11f0-a758-000c2943d053

In [ ]:
from datetime import datetime


print()

13-01-2026